### ISSUE TITLE
Using memes with WSL

### ISSUE THREAD

**Issue by eladzis** [snystrom/dremeR#106]
Hello
I'm trying to use the library on a windows OS with MEME installed via WSL
I can run the `streme `command on the bash command line but when I try to use it through R it doesn't find the command:

Error in `process_initialize(self, private, command, args, stdin, stdout, …`:
! Native call to `processx_exec` failed
Caused by error in `chain_call(c_processx_exec, command, c(command, args), pty, pty_options, …`:
! Command '\\wsl.localhost/Ubuntu-20.04/home/user/meme/bin/streme' not found @win/processx.c:982 (processx_exec)
---
Backtrace:
 1. memes::runStreme(sequ_1_test, "shuffle")
 2. memes:::runStreme.default(sequ_1_test, "shuffle")
 3. processx::run(command, flags, spinner = TRUE, error_on_status = F…
 4. process$new(command, args, echo_cmd = echo_cmd, wd = wd, windows_…
 5. local initialize(...)
 6. processx:::process_initialize(self, private, command, args, stdin, stdout, …
 7. processx:::chain_call(c_processx_exec, command, c(command, args), pty, pty_o…
 8. | base::withCallingHandlers(do.call(".Call", list(.NAME, ...)), error = f…
 9. | base::do.call(".Call", list(.NAME, ...))
10. | base::.handleSimpleError(function (e) …
11. | local h(simpleError(msg, call))
12. | processx:::throw_error(err, parent = e)
 

I'd appreciate any help you can give,

Elad

**Comment by snystrom** [comment]
Are you running R inside WSL or from windows? In order to use the meme suite features of `memes`, R must be running inside WSL. 

If you are running R in WSL and you think this is a different issue, could you post the output of `sessionInfo()`?

**Comment by snystrom** [comment]
Also if you could post the output of `check_meme_install()` that would be helpful.

**Comment by eladzis** [comment]
When I ran the library through the wsl it worked
Thanks
