### ISSUE TITLE
rna option not recognised for runStreme

### ISSUE THREAD

**Issue by CharlotteAnne** [snystrom/dremeR#119]
Hi,

I am having an issue where the rna option isn't recognised by runStreme. My command is:
`memes::runStreme(down_prox_seq_200, ctrl_prox_seq_200, outdir = tempdir(), minw=3, maxw=5, rna=TRUE)`

But in the output table the alphabet column is "DNA" and strand is "+-"

The version I am using is noted below:
```
packageVersion("memes")
[1] ‘1.10.0’
```

Alternatively, the rna=TRUE is recognised in runDREME.

Thanks for any help,
Charlotte

**Comment by snystrom** [comment]
Hi Charlotte,

Could you try instead setting `alph="rna"`? This should do the same thing as the Boolean flag, and is in general the best way to hint the alphabet to use to any `run` function in `{memes}`. This is the one exception for how calling the functions in R slightly differs from the other command line arguments.

Hope this helps, let me know if it resolved your issue or not.

**Comment by CharlotteAnne** [comment]
Yes perfect!! Thanks so much!
