### ISSUE TITLE
runAme fails to import sequences - Error in !sequences : invalid argument type 

### ISSUE THREAD

**Issue by withermatt** [snystrom/dremeR#121]
Hi, when running AME in R with runAme and setting sequences = TRUE, I believe the 'sequences' variable is being set to the path to the sequences.tsv file. 
Therefore importAme cannot evaluate this as a logical and throws the error. 

`res <- runAme(input = x, control = NA, database = enriched_motifs, silent = TRUE, method = "fisher", sequences = TRUE")
Error in !sequences : invalid argument type
`

I believe the issue is here (lines 182-185 of ame.R:
`if (!sequences | method != "fisher"){return(data)}`

 `if (sequences & method == "fisher"){
    seq <- importAmeSequences(sequences)
`

I can manually import the sequences into my AME output. But would be great to fix this in the pacakge. Thank you!

**Comment by snystrom** [comment]
Interesting. I'll work on a fix here, this really should be caught by unit tests, too. :woman_facepalming: 

Thanks for reporting!

**Comment by snystrom** [comment]
hey @withermatt sorry for the delay (no longer get paid to maintain this pkg, so slow going...), but I think this latest change fixes it. I pushed this to bioc devel branch, and will backport to `RELEASE_3_19` if the devel bioc build looks good.

In the mean time, you could `remotes::install_github('snystrom/memes')` if you wanted to use the fix.

Thanks again for reporting, I really appreciate it & the time you spent digging into the issue yourself helped me get this one across the line.
